# Generated by Django 2.2.5 on 2021-02-03 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_name', models.CharField(max_length=10)),
                ('School_address', models.CharField(max_length=10, unique=True)),
                ('School_logo', models.FileField(blank=True, null=True, upload_to='media/img')),
                ('School_unique_id', models.CharField(max_length=10)),
                ('Admin_img', models.FileField(blank=True, null=True, upload_to='media/img')),
                ('Contact_person_First_name', models.CharField(blank=True, max_length=25, null=True)),
                ('Contact_person_Last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('is_email_verify', models.BooleanField(blank=True, default=False, null=True)),
                ('is_mobile_verify', models.BooleanField(blank=True, default=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('otp_forgot_password', models.CharField(blank=True, max_length=25, null=True)),
                ('School_which_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_name', models.CharField(max_length=10)),
                ('Teacher_img', models.FileField(blank=True, null=True, upload_to='media/img')),
                ('Teacher_Last_name', models.CharField(max_length=10)),
                ('Dob', models.DateTimeField(blank=True, max_length=10, null=True)),
                ('Teacher_gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=25, null=True)),
                ('Teacher_unique_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('is_email_verify', models.BooleanField(blank=True, default=False, null=True)),
                ('is_mobile_verify', models.BooleanField(blank=True, default=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('otp_forgot_password', models.CharField(blank=True, max_length=25, null=True)),
                ('Teacher_School', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jassmin_app.School')),
                ('which_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(max_length=10, unique=True)),
                ('Subject_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('Subject_Teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jassmin_app.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=10)),
                ('Student_img', models.FileField(blank=True, null=True, upload_to='media/img')),
                ('Student_Last_name', models.CharField(max_length=10)),
                ('Student_mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('Dob', models.DateTimeField(blank=True, max_length=10, null=True)),
                ('Student_gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=25, null=True)),
                ('Student_unique_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('is_email_verify', models.BooleanField(blank=True, default=False, null=True)),
                ('is_mobile_verify', models.BooleanField(blank=True, default=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('otp_forgot_password', models.CharField(blank=True, max_length=25, null=True)),
                ('Student_School', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jassmin_app.School')),
                ('which_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_address', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_salary', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_post', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('which_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Class_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_t_name', models.CharField(blank=True, max_length=10, null=True)),
                ('Class_t_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('Class_t_Subject', models.ManyToManyField(to='jassmin_app.Subject')),
                ('Class_t_teacher', models.ManyToManyField(to='jassmin_app.Teacher')),
                ('Class_t_tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
